export const GET_BOARD_FORM_REQUEST = 'GET_BOARD_FORM_REQUEST'
export const CREATE_BOARD_FORM_REQUEST = 'CREATE_BOARD_FORM_REQUEST'
export const UPDATE_BOARD_FORM_REQUEST = 'UPDATE_BOARD_FORM_REQUEST'
