export const ADD_NEW_CLIENT = 'ADD_NEW_CLIENT'
export const REMOVE_CLIENT = 'REMOVE_CLIENT'
export const SELECT_CLIENT = 'SELECT_CLIENT'
export const CHANGE_CLIENT_NAME = 'CHANGE_CLIENT_NAME'
export const GET_CLIENTS = 'GET_CLIENTS'
export const GET_CLIENT = 'GET_CLIENT'

export const SET_CLIENTS = 'SET_CLIENTS'
export const UPDATE_CLIENT = 'UPDATE_CLIENT'
