export const MEGAFON_CREATE_INTEGRATION = 'MEGAFON_CREATE_INTEGRATION'
export const MEGAFON_CHECK_INTEGRATION = 'MEGAFON_CHECK_INTEGRATION'
export const MEGAFON_REMOVE_CORP_INTEGRATION = 'MEGAFON_REMOVE_CORP_INTEGRATION'
export const SET_MEGAFON_INTEGRATION = 'SET_MEGAFON_INTEGRATION'
